name: Python tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask==3.0.3 Flask-SQLAlchemy requests

      - name: Run tests
        run: |
          python testsprite.py
